# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc614ef6104929990386ffdf5c884902785f265a9b9b86f4c7c81df68ab31aeafcb77fa6ff6fa86c0ba56f4df0d3dcd3616034bb3436fd3145e6fb1229feaa28

test:
  secret_key_base: 469abd36bba9373668839d44347f4816b416405e5f007a820302a811748ab895c1becab448890891de5fd1ea29ebd41db9ec3b9e2047fbc147ed0ffc208cad68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
